---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
driver:
  name: docker
platforms:
  - name: ansible-role-drall-1604
    image: geerlingguy/docker-ubuntu1604-ansible
    pre_build_image: true

  - name: ansible-role-drall-2004
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true

provisioner:
  name: ansible
