---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
driver:
  name: docker
platforms:
  - name: ansible-role-drall-1604
    image: ubuntu
    image_version: 16.04
    volume_mounts:
      - ${MOLECULE_APTPROXY_PATH}:/etc/apt/apt.conf.d/00aptproxy

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
